"""
Email dispatcher for sending language-aware, topic-filtered reports to subscribers.

This module handles the batch dispatch of markdown reports to subscribers
based on their city, topic, and language preferences. Unlike the email_sender.py
node (which is part of the pipeline chain), this dispatcher is called after all
pipelines complete and works with the cached reports dictionary.

Each subscriber receives a personalized email in their preferred language,
containing only the reports matching their selected topics.
"""

import json
import os
import time
import queue
import logging
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from typing import Any

from utils.supabase_client import get_all_subscribers_with_cities_and_topics
from utils.report.translator import LANG_MAP
from utils.email import (
    SMTPConnectionPool,
    convert_markdown_to_html,
    render_template,
    send_single_email,
    is_email_configured,
)

logger = logging.getLogger(__name__)


def save_failures(failures: list[dict]):
    """Save email delivery failures to a JSON file.

    Args:
        failures: List of failure records
    """
    if not failures:
        return
    failures_path = os.path.join(os.path.dirname(__file__), "..", "email_failures.json")
    with open(failures_path, "w") as f:
        json.dump(failures, f, indent=2)
    logger.warning(f"Saved {len(failures)} email delivery failures to {failures_path}")


def _build_subscriber_markdown(
    subscriber_topics: list[str],
    city_reports: dict[str, str],
) -> str:
    """Build combined markdown from matching topic reports for a subscriber.

    Args:
        subscriber_topics: List of topic names the subscriber is interested in
        city_reports: Dict mapping topic name to markdown report for the subscriber's city

    Returns:
        Combined markdown string with topic sections, or empty string if no matches
    """
    sections = []
    for topic in subscriber_topics:
        topic_report = city_reports.get(topic)
        if topic_report:
            sections.append(topic_report)

    return "\n\n---\n\n".join(sections)


def _build_translated_subscriber_markdown(
    subscriber_topics: list[str],
    city: str,
    lang_code: str,
    translations: dict[str, dict[str, dict[str, str]]],
) -> str:
    """Build combined translated markdown for a subscriber's preferred language.

    Args:
        subscriber_topics: List of topic names the subscriber is interested in.
        city: The subscriber's city.
        lang_code: Target language code (e.g. "ES", "FR").
        translations: Nested dict {city: {topic: {lang: translated_markdown}}}.

    Returns:
        Combined translated markdown, or empty string if no translations available.
    """
    city_translations = translations.get(city, {})
    if not city_translations:
        return ""

    sections = []
    for topic in subscriber_topics:
        translated = city_translations.get(topic, {}).get(lang_code, "")
        if translated:
            sections.append(translated)

    return "\n\n---\n\n".join(sections)


def dispatch_emails_to_subscribers(
    reports: dict[str, dict[str, str]],
    translations: dict[str, dict[str, dict[str, str]]] | None = None,
) -> dict[str, Any]:
    """
    Query all subscribers and send each a personalized report in their preferred language.

    This function:
    1. Validates that reports is not empty
    2. Queries subscribers with their city, topic, and language preferences
    3. For each subscriber, selects the report in their preferred language:
       - English (or NULL): sends the original English report
       - Spanish/French: sends the translated version if available, falls back to English
    4. Combines matching topic reports into a single personalized email
    5. Tracks delivery statistics and failures

    Args:
        reports: Nested dictionary mapping city -> topic -> markdown report.
                 Generated from report_cache.get_all().
        translations: Optional nested dict mapping city -> topic -> lang -> translated markdown.
                      Generated by report_translator.translate_all_reports().

    Returns:
        Dictionary with delivery statistics.
    """

    # Check if email is configured
    if not is_email_configured():
        logger.info("Email configuration incomplete; skipping email dispatch")
        return {
            "total_sent": 0,
            "by_city": {},
            "missing_reports": [],
            "delivery_failures": [
                "Email not configured - missing SMTP_EMAIL or SMTP_APP_PASSWORD"
            ],
        }

    # Validate input
    if not reports:
        logger.warning("No reports available for dispatch (reports is empty)")
        return {
            "total_sent": 0,
            "by_city": {},
            "missing_reports": [],
            "delivery_failures": ["No reports available for dispatch"],
        }

    # Query all subscribers with their city, topic, and language preferences
    try:
        subscribers = get_all_subscribers_with_cities_and_topics()
    except Exception as e:
        logger.error(f"Failed to query subscribers: {e}")
        return {
            "total_sent": 0,
            "by_city": {},
            "missing_reports": [],
            "delivery_failures": [f"Failed to query subscribers: {str(e)}"],
        }

    if not subscribers:
        logger.info("No subscribers found")
        return {
            "total_sent": 0,
            "by_city": {},
            "missing_reports": [],
            "delivery_failures": [],
        }

    logger.info(f"Dispatching topic-filtered reports to {len(subscribers)} subscriber(s)")

    # Build per-subscriber email content and track missing reports
    send_queue: list[dict[str, str]] = []
    missing_reports: list[dict] = []

    for subscriber in subscribers:
        contact = subscriber.get("contact")
        city = subscriber.get("city")
        topics = subscriber.get("topics", [])
        preferred_language = subscriber.get("preferred_language")

        if not contact or not city:
            logger.warning(f"Subscriber missing contact or city: {subscriber}")
            continue

        if not city.strip():
            logger.warning(f"Subscriber has empty city name: {subscriber}")
            continue

        city_reports = reports.get(city, {})

        if not city_reports:
            logger.warning(f"No reports available for city: {city}")
            missing_reports.append({
                "email": contact,
                "city": city,
                "topics": topics,
                "reason": "No reports available for city",
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })
            continue

        if not topics:
            logger.warning(f"Subscriber {contact} has no topic preferences")
            missing_reports.append({
                "email": contact,
                "city": city,
                "topics": [],
                "reason": "No topic preferences set",
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })
            continue

        # Determine which content to send based on preferred_language
        lang_code = LANG_MAP.get(preferred_language or "") if preferred_language else None

        if lang_code and translations:
            # Try to build translated content for the preferred language
            combined_markdown = _build_translated_subscriber_markdown(
                topics, city, lang_code, translations
            )
            if not combined_markdown:
                # Fall back to English if translation is not available
                logger.info(
                    f"No {preferred_language} translation for {contact} ({city}); "
                    f"falling back to English"
                )
                combined_markdown = _build_subscriber_markdown(topics, city_reports)
        else:
            # English or no preference — use original reports
            combined_markdown = _build_subscriber_markdown(topics, city_reports)

        if not combined_markdown:
            logger.warning(
                f"No matching topic reports for subscriber {contact} "
                f"(city={city}, topics={topics})"
            )
            missing_reports.append({
                "email": contact,
                "city": city,
                "topics": topics,
                "reason": "No reports match subscriber topics",
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })
            continue

        # Convert to HTML and queue for sending
        html_content = convert_markdown_to_html(combined_markdown)
        html_body = render_template(html_content)

        send_queue.append({
            "contact": contact,
            "city": city,
            "html_body": html_body,
        })

    if not send_queue:
        logger.info("No emails to send after topic filtering")
        return {
            "total_sent": 0,
            "by_city": {},
            "missing_reports": missing_reports,
            "delivery_failures": [],
        }

    # Set up email infrastructure
    try:
        pool = SMTPConnectionPool(pool_size=10)
    except RuntimeError as e:
        logger.error(f"Failed to initialize SMTP connection pool: {e}")
        return {
            "total_sent": 0,
            "by_city": {},
            "missing_reports": missing_reports,
            "delivery_failures": [f"SMTP pool initialization failed: {str(e)}"],
        }

    failures_queue: queue.Queue = queue.Queue()

    delivery_stats: dict[str, Any] = {
        "total_sent": 0,
        "by_city": {},
        "missing_reports": missing_reports,
        "delivery_failures": [],
    }

    with pool:
        # Send emails in waves to avoid rate limiting
        waves = [send_queue[i : i + 100] for i in range(0, len(send_queue), 100)]

        for wave in waves:
            with ThreadPoolExecutor(max_workers=10) as executor:
                futures = []
                for item in wave:
                    future = executor.submit(
                        send_single_email,
                        pool,
                        item["contact"],
                        f"NV Local Report - {item['city']}",
                        item["html_body"],
                        failures_queue,
                    )
                    futures.append((future, item))

                for future, item in futures:
                    success = future.result()
                    if success:
                        city = item["city"]
                        delivery_stats["by_city"][city] = (
                            delivery_stats["by_city"].get(city, 0) + 1
                        )
                        delivery_stats["total_sent"] += 1

            time.sleep(1)

    # Extract failures from queue
    delivery_failures = []
    while not failures_queue.empty():
        try:
            delivery_failures.append(failures_queue.get_nowait())
        except queue.Empty:
            break

    # Save all failures
    all_failures = delivery_failures + missing_reports
    save_failures(all_failures)

    delivery_stats["delivery_failures"] = delivery_failures

    logger.info(
        f"Email dispatch complete: {delivery_stats['total_sent']} sent, "
        f"{len(delivery_failures)} delivery failures, "
        f"{len(missing_reports)} missing reports"
    )

    return delivery_stats